restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restaurantApp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/restaurantApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('menu/',views.menu,name="menu"),
	path('viewMenu/',views.viewMenu,name="viewMenu"),
	path('',views.mainpg,name="home"),
	path('update_item/',views.updateItem,name="update_item"),
	path('loggedUser/',views.mainpgLog,name="loggedUser"),
	path('dashboard-admin/',views.dashboard_admin,name="dashboard-admin"),
	path('login/',views.loginPage,name="login"),
	path('logout/',views.logoutUser,name="logout"),
	path('contact/',views.contact,name="contact"),
	path('registration/',views.registration,name="registration"),
	path('booking/',views.booking,name="booking"),
	path('account/',views.account,name='account'),
	path('restaurants/',views.restaurants,name="restaurants"),
	path('cart/',views.cart,name="cart"),
	path('checkout/',views.checkout,name="checkout"),
	path('test/',views.test,name="test"),
]

restaurant/restaurantApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid
from datetime import date

# Create your models here.
# null True and blank True are almost the same, except in the case
# of TextField & CharField, which are not saved as NULL but as '' in db
class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length=200,null=True)
	phone = models.CharField(max_length=10,null=True)
	email = models.CharField(max_length=200,null=True)
	date_created = models.DateTimeField(auto_now_add=True,null=True)

	def __str__(self):
		return self.name

	@classmethod
	def create(cls,user,name,email):
		customer = cls(user=user,name=name,phone='',email=email)
		return customer

class StaffMember(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	first_name = models.CharField(max_length=15)
	last_name = models.CharField(max_length=15)
	#staffId
	phone = models.CharField(max_length=10)
	email = models.CharField(max_length=100)

	def __str__(self):
		return (self.last_name.upper() + ", " + self.first_name)

	def save(self, *args, **kwargs):
		if self.user.is_staff:
			self.email = self.user.email
			super(StaffMember, self).save(*args,**kwargs)


class Restaurant(models.Model):
	address = models.CharField(max_length=200,null=False)
	city = models.CharField(max_length=50,null=False)
	state = models.CharField(max_length=3,null=False)
	postcode = models.CharField(max_length=4,null=False)
	opening_time = models.IntegerField()
	closing_time = models.IntegerField()

	def __str__(self):
		return self.city

class MenuItem(models.Model):
	CATEGORY = (
		('Entree','Entree'),
		('Salads','Salads'),
		('Main Course','Main Course'),
		('Dessert','Dessert'),
		('Drinks','Drinks'),
	)

	name = models.CharField(max_length=200,null=True)
	price = models.FloatField()
	portion_size = models.CharField(max_length=10,null=True)
	desc = models.CharField(max_length=750,null=True)
	image = models.ImageField(null=True, blank=True)
	#category = models.ForeignKey(Category,null=True,blank=True,on_delete=models.CASCADE)

	def __str__(self):
		return self.name


class Booking(models.Model):
	"""Assuming a customer can make a single booking at a given time"""
	customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True, blank=True)
	name = models.CharField(max_length=100,null=True,blank=True)
	phone = models.CharField(max_length=10,null=True)
	date_created = models.DateField(auto_now_add=True)
	booking_date = models.DateField(null=True,blank=True)
	booking_time = models.TimeField(null=True,blank=True)
	complete = models.BooleanField(default=False,null=True,blank=False)
	number_of_guests = models.IntegerField(default=1,
        validators=[
            MaxValueValidator(20),
            MinValueValidator(1)
        ]
	)

	booking_ref = models.CharField(max_length=15,null=True,blank=True)

	def __str__(self):
		return (self.customer.name + " (" + str(self.id) + ")")

	@classmethod
	def create(cls,customer,name,phone,given_date,given_time,guests,transaction_id):
		booking = cls(customer=customer,name=name,phone=phone,booking_date=given_date,booking_time=given_time,complete=False,number_of_guests=guests,booking_ref=transaction_id)
		return booking

	@property
	def booking_complete(self):
		if self.booking_date > date.today():
			complete = True

	@property
	def booking_event(self):
		if self.booking_time.strftime("%H") < "12":
			return 'Breakfast'
		elif self.booking_time.strftime("%H") < "17":
			return 'Lunch'
		return 'Dinner'

class Table(models.Model):
	restaurant = models.ForeignKey(Restaurant,on_delete=models.CASCADE)
	capacity = models.IntegerField(validators=[MaxValueValidator(10),MinValueValidator(2)])

	def __str__(self):
		return str(self.id)


class Category(models.Model):
	name = models.CharField(max_length=200,null=True)
	category_item = models.ForeignKey(MenuItem,null=True,blank=True,on_delete=models.CASCADE)

	def __str__(self):
		return self.name


#create a complete order based on what is already in the cart? i.e. separate class
#or cart itself

class Order(models.Model):
	id = models.AutoField(primary_key=True)
	STATUS = (
		('Pending','Pending'),
		('Out for delivery','Out for delivery'),
		('Delivered','Delivered'),
		('Served','Served'),
		('Ready for Pickup','Ready for Pickup'),
	)
	customer = models.ForeignKey(Customer,null=True,on_delete=models.CASCADE)
	booking = models.OneToOneField(Booking, on_delete=models.CASCADE, null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False,null=True,blank=False)
	status = models.CharField(max_length=200,null=True,choices=STATUS)

	def __str__(self):
		return str(self.id)

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

	

class OrderItem(models.Model):
	order = models.ForeignKey(Order,null=True,on_delete=models.CASCADE)
	menu_item = models.ForeignKey(MenuItem,null=True,on_delete=models.CASCADE)
	quantity = models.IntegerField(default=0,null=True,blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		total = self.menu_item.price * self.quantity
		return total

restaurant/restaurantApp/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import StaffMember
from .models import Booking
from django.contrib.auth.forms import UserCreationForm
from datetimepicker.widgets import DateTimePicker
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

class StaffForm(ModelForm):
    phone = forms.CharField(max_length=10,min_length=10)
    class Meta:
        model = StaffMember
        fields = ['first_name','last_name','phone','email']

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class BookingForm(ModelForm):
    phone = forms.CharField(max_length=10,min_length=10)
    name = forms.CharField(max_length=100)
    class Meta:
        model = Booking
        fields = ['booking_date','booking_time','number_of_guests','name','phone']
        widgets = {'booking_date':DateInput(),'booking_time':TimeInput()}

    def __init__(self, *args, **kwargs):
        super(BookingForm,self).__init__(*args, **kwargs)
        self.fields['number_of_guests'].widget.attrs.update({'min': 1, 'max':20})

restaurant/restaurantApp/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from .models import *
from django.http import JsonResponse, HttpResponse
import json
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from .forms import BookingForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.db.models.functions import Concat
from django.contrib import messages
from .decorators import unauthenticated_user,allowed_user,admin_only
from .filters import MenuFilter
import uuid
from datetime import date

# Create your views here.
def menu(request):
	menu_items = MenuItem.objects.all()

	#only create an order if 1) user is authenticated 2) has a booking
	if request.user.is_authenticated:
		customer = request.user.customer

		all_bookings = list(Booking.objects.filter(customer=customer))
		current_bookings = list(filter(lambda booking: (booking.booking_date > date.today()), all_bookings))

		if len(current_bookings) == 1:
			order, created = Order.objects.get_or_create(customer=customer,booking=current_bookings[0],complete=False,status='Pending')
			items = order.orderitem_set.all()
			cartItems = order.get_cart_items
		else:
			print("You need to make a booking first. An order can be made subsequently.")
	else:
		items = []
		order = {'get_cart_items':0, 'get_cart_total':0}
		cartItems = order['get_cart_items']

	itemFilter = MenuFilter(request.GET,queryset=menu_items)
	menu_items = itemFilter.qs

	context = {'menu_items':menu_items,'order':order,'itemFilter':itemFilter}
	return render(request,'restaurantApp/menu.html',context)

def updateItem(request):
	try:
		data = json.loads(request.body)
		itemId = data['itemId']
		action = data['action']
		print('Action:',action)
		print('Item ID:',itemId)

		customer = request.user.customer
		item = MenuItem.objects.get(id=itemId)
		order, created = Order.objects.get_or_create(customer=customer,complete=False,status='Pending')
		#if the order already exists, then we do not make a new Order
		#just add/substract from it
		orderItem, created = OrderItem.objects.get_or_create(order=order,menu_item=item)
	
		if action == 'add':
			orderItem.quantity += 1
		elif action == 'remove':
			orderItem.quantity -= 1
		orderItem.save()

		if orderItem.quantity <= 0:
			orderItem.delete()

		return JsonResponse('Item was added',safe=False)

	except json.decoder.JSONDecodeError:
		print("There was a problem accessing the website data.")
	return JsonResponse('Oops...',safe=False)

@allowed_user(allowed_roles=['admin','Staff'])
def dashboard_admin(request):
	#menu_items = MenuItem.objects.all()
	orders = Order.objects.all()
	customers = Customer.objects.all()

	staff_member = StaffMember.objects.all()
	total_customers = customers.count()
	total_orders = orders.count()
	served = orders.filter(status='Served').count()
	pending = orders.filter(status='Pending').count()

	context = {'orders':orders,'customers':customers,'staff_member':staff_member,'total_orders':total_orders,'total_customers':total_customers,'served':served,'pending':pending}
	return render(request,'restaurantApp/dashboard-admin.html',context)

def mainpg(request):
	context = {}
	return render(request,'restaurantApp/mainpg.html',context)

@login_required(login_url='login')
@allowed_user(allowed_roles=['customer'])
def mainpgLog(request):
	context = {}
	return render(request,'restaurantApp/mainpgLog.html',context)

@unauthenticated_user
def loginPage(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		#ensure the user can be authenticated to registered details
		user = authenticate(request,username=username,password=password)

		#if authenticated
		if user is not None:
			login(request,user)
			return redirect('home')
		else:
			messages.info(request,'Username or password is incorrect.')
		
	context = {}
	return render(request,'restaurantApp/login.html',context)

def logoutUser(request):
	logout(request)
	return redirect('login')

@unauthenticated_user
def registration(request):
	form = CreateUserForm()
	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		# if entered data is valid
		if form.is_valid():
			# form based on User model, saving will create a new User
			user = form.save()
			username = form.cleaned_data.get('username')
			email = form.cleaned_data.get('email')
			cust_group = Group.objects.get(name='customer')
			user.groups.add(cust_group)
			customer = Customer.create(user,username,email)
			customer.save()
			messages.success(request,'Account was created for ' + username)
			return redirect('login')
	else:
		form = CreateUserForm()
	context = {'form': form}
	return render(request,'restaurantApp/registration.html',context)

def addStaff(request):
	form = StaffForm()
	if request.method == 'POST':
		staff_reg_form = StaffForm(request.POST)
		staff_name = form.cleaned_data.get('first_name')
		if form.is_valid():
			staff_member = form.save()
			messages.success(request,'New staff account created for ' + staff_name)
			return redirect('dashboard-admin')

@login_required(login_url='login')
def booking(request):
	booking_form = BookingForm()
	if request.method == 'POST':
		booking_form = BookingForm(request.POST)
		if booking_form.is_valid():
			customer = request.user.customer
			name = booking_form.cleaned_data.get('name')
			phone = booking_form.cleaned_data.get('phone')
			booking_date = booking_form.cleaned_data.get('booking_date')
			booking_time = booking_form.cleaned_data.get('booking_time')
			number_of_guests = booking_form.cleaned_data.get('number_of_guests')

			bdate = str(booking_date)
			btime = booking_time.strftime('%H:%M')
			bdate = bdate.replace('-','')
			btime = btime.replace(':','')
			num_guests = str(number_of_guests)
			initials = ''.join([x[0] for x in name.split()])
			initials = initials.upper()
			transaction_id = initials + bdate + btime + num_guests

			prev_bookings = Booking.objects.filter(customer=customer, booking_date__range=["2021-01-01", date.today()])
			all_bookings = Booking.objects.filter(customer=customer)
			#if no new bookings exist, only then can a user make a booking
			if(all_bookings.count() - prev_bookings.count() == 0):
				booking = Booking.create(customer,name,phone,booking_date,booking_time,number_of_guests,transaction_id)
				booking.save()
				return redirect('menu')
			else:
				messages.warning(request,'A booking already exists under your account. Please try again another time.')
	context = {'booking_form':booking_form}	 
	return render(request,'restaurantApp/booking.html',context)

@login_required(login_url='login')
@allowed_user(allowed_roles=['customer'])
def account(request):
	customer = request.user.customer
	all_bookings = list(Booking.objects.filter(customer=customer))
	prev_bookings = list(filter(lambda booking: (booking.booking_date < date.today()), all_bookings))
	next_booking = list(filter(lambda booking: (booking not in prev_bookings), all_bookings))

	context = {'prev_bookings':prev_bookings,'next_booking':next_booking}
	return render(request,'restaurantApp/account.html',context)


def restaurants(request):
	context = {}
	return render(request,'restaurantApp/restaurants.html',context)

def contact(request):
	context = {}
	return render(request,'restaurantApp/contact.html',context)

def checkout(request):
	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer,complete=False,status='Pending')
		booking = Booking.objects.get(customer=customer,date_created=date.today())
		items = order.orderitem_set.all()
	else:
		items = []
		order = {'get_cart_items':0, 'get_cart_total':0}
	#remove loop
	for i in range(items.count()):
		print(items[i])
	context = {'items':items, 'order':order, 'booking':booking}
	return render(request,'restaurantApp/checkout.html',context)

def cart(request):
	if request.user.is_authenticated:
		customer = request.user.customer
		order, created = Order.objects.get_or_create(customer=customer,status='Pending',complete=False)
		items = order.orderitem_set.all()
	else:
		items = []
		order = {'get_cart_items':0, 'get_cart_total':0}
	#remove loop
	for i in range(items.count()):
		print(items[i])
	context = {'items':items, 'order':order}
	return render(request,'restaurantApp/cart.html',context)

def test(request):
	context = {}
	return render(request,'restaurantApp/test.html',context)

def viewMenu(request):
	menu_items = MenuItem.objects.all()
	itemFilter = MenuFilter(request.GET,queryset=menu_items)
	menu_items = itemFilter.qs

	context = {'menu_items' : menu_items, 'itemFilter':itemFilter}
	return render(request,'restaurantApp/viewMenu.html',context)

restaurant/restaurantApp/templates/restaurantApp/booking.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>
        Le Bistrot d'Andre
    </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initialscale=1.0">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fontawesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <!--Message Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        body {
            font-family: latha;
            color: white;
            background-image: linear-gradient(rgba(1,1,1,0.5), rgba(0,0,0,0), rgba(0,0,0,0), rgba(1,1,1,0.5)), url('{% static 'images/restaurantBG1.png' %}');
            height: 100%;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }

        .hello-msg {
            font-size: 18px;
            color: #fff;
            margin-right: 20px;
        }

        .box {
            overflow: hidden;
            background-color: #333;
        }

        .box a {
            float: right;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 18px;
            display: inline-block;
        }

        .box a:hover {
            background-color: #4CAF50;
            color: black;
        }

        .box a.active {
            background-color: #4CAF50;
            color: white;
        }

        .header {
            background: #000;
            color: #8a8a8a;
            font-size: 14px;
            margin-left: auto;
            margin-right: auto;
            padding-top: 10px;
            padding-bottom: 5px;
            border-color: white;
            border-style: solid;
            border-top-width: 5px;
            border-bottom-width: 5px;
            border-left: 0px;
            border-right: 0px;
            font-family: 'Josefin Sans';
        }

        .footer {
            background: #000;
            color: #8a8a8a;
            font-size: 14px;
            margin-left: auto;
            margin-right: auto;
            border-top-color: white;
            border-top-style: solid;
            border-top-width: 5px;
            border-top-color: white;
        }

        .logos {
            padding: 10px;
            text-align: center;
            margin-bottom: 10px;
            align-items: center;
        }

        .row {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }


        .btn {
            display: inline-block;
            background: #ff523b;
            display: inline-block;
            color: #fff;
            padding: 8px 15px;
            margin: 30px 10px;
            border-radius: 30px;
            transition: background 0.5s;
        }

        .btn:hover {
            color: #fff;
            padding: 8px 15px;
            margin: 30px 10px;
            border-radius: 30px;
            transition: background 0.5s;
            background: #563434;
        }

        .btn2 {
            border-width: 0;
            background: #ff523b;
            display: inline-block;
            color: #fff;
            padding: 8px 8px;
            border-radius: 100%;
            transition: background 0.5s;
            width: 40px;
        }

        .btn2:hover {
            border-width: 0;
            color: #fff;
            padding: 8px 8px;
            border-radius: 100%;
            transition: background 0.5s;
            background: #563434;
            width: 40px;
        }

        .midtext {
            color:#8a8a8a;
            text-align: center;
            top: 50%;
            margin: auto;
            background: black;
            border-color: white;
            border-style: solid;
            border-width: 5px;
            border-radius: 10px;
            padding: 20px;
            width: 500px;
        }

        .table tr,td{
            border-bottom:1px solid white;
            color:#8a8a8a;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #id_number_of_guests{
            width: 50px;
            height: 30px;
        }
    </style>

</head>
<body>

    <div class="box">
        <ul type="none">
            <li style="float:left">
                <a href="{% url 'home' %}">
                    <img src="{% static 'images/logo.png' %}" width="60" height="25">
                </a>
            </li>

            <li style="float:left"><a href="{% url 'home' %}"> Home </a></li>
            <!--fix required: only continue booking button will redirect to menu...-->
            <li style="float:left"><a href="{% url 'viewMenu' %}"> Menu </a></li>
            <li style="float:left"><a href="{% url 'booking' %}"> Booking </a></li>
            <li style="float:left"><a href="#contact"> Contact </a></li>
            {% if request.user.is_active %}
            <li><a href="{% url 'logout' %}"> Logout </a></li>
                {% if request.user.is_staff %}
                <li><a href="{% url 'dashboard-admin' %}"> Account </a></li>
                {% else %}
                <li><a href="{% url 'account' %}"> Account </a></li>
                {% endif %}
            {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'dashboard-admin' %}"> Staff </a></li>
            {% endif %}

        </ul>
    </div>
    <div class="header">
        <div class="row">
            <h3>Step 1: Booking</h3>
        </div>
    </div>
    {% include 'restaurantApp/includes/messages.html' %}
    <br>

    <div class="midtext">
        <h3>Please fill out the following:</h3>
        <br>
        <form action="" method="POST">
            {% csrf_token %}
            <table class="table">
            <tr>
                <td>Choose date: </td>
                <td>{{booking_form.booking_date}}<td>
            </tr>
            <tr>
                <td>Choose time: </td>
                <td>{{booking_form.booking_time}}<td>
            </tr>
            <tr>
                <td>Number of attendees: </td>
                <td><button class="btn2" onclick="decr()">-</button> {{booking_form.number_of_guests}} <button class="btn2" onclick="incr()">+</button><td>
                <script>
                    function incr() {
                        document.getElementById('id_number_of_guests').stepUp();
                    } function decr() {
                        document.getElementById('id_number_of_guests').stepDown();
                    }
                </script>
            </tr>
            <tr>
                <td>Your name: </td>
                <td>{{booking_form.name}}<td>
            </tr>
            <tr>
                <td>Phone number: </td>
                <td>{{booking_form.phone}}<td>
            </tr>
            </table>
            {{form.errors}}
            <input class="btn" type="submit" value="Continue with Booking"> 
        </form>
    </div>

    <br><br><br><br><br><br><br><br>
    <div class="footer">
        <div class="row">
            <div class="logos">
                <h3 id="contact">Contact Us Here</h3> <p></p>
                <a href="https://www.instagram.com/">
                    <img src="{% static 'images/instagram.png' %}" width="75" height="75">
                </a>
                <a href="https://www.facebook.com/">
                    <img src="{% static 'images/facebook.png' %}" width="75" height="75">
                </a>
                <a href="https://www.yelp.com/">
                    <img src="{% static 'images/yelp.png' %}" width="75" height="75">
                </a>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>

restaurant/restaurantApp/templates/restaurantApp/profile-status.html
<br>

<div class="row">
	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="total-orders">
			  	<div class="card-header">
			  		<h5 class="card-title">Loyalty Points</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">25</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-delivered">
			  	<div class="card-header">
			  		<h5 class="card-title">Total Bookings</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">{{prev_bookings|length}}</h3>
			  	</div>
			</div>
		</div>
	</div>

	<div class="col">
		<div class="col-md">
			<div class="card text-center text-white  mb-3" id="orders-pending">
			  	<div class="card-header">
			  		<h5 class="card-title">Orders Pending</h5>
			  	</div>
			  	<div class="card-body">
			    	<h3 class="card-title">1</h3>
			  	</div>
			</div>
		</div>
	</div>
</div>

restaurant/restaurantApp/templates/restaurantApp/search.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <title>Andre's Bistro</title>
</head>

<body>
{% for result in results %}

    <p>{{result.name}}</p>

{% endfor %}
</body>
</html>